package Week9.KalkulatorBilanganKompleks;

import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Clipboard;
import javax.swing.*;
import java.util.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class GUIkompleks extends javax.swing.JFrame {

    private BilanganKompleks z1 = new BilanganKompleks(0,0);
    private BilanganKompleks z2 = new BilanganKompleks(0,0);
    private BilanganKompleks hasil = new BilanganKompleks(0,0);
    
    public GUIkompleks() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        fieldZ1 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        fieldZ3 = new javax.swing.JTextField();
        fieldZ4 = new javax.swing.JTextField();
        fieldZ5 = new javax.swing.JTextField();
        fieldZ6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jClear = new javax.swing.JButton();
        jModulus = new javax.swing.JButton();
        jArgumen = new javax.swing.JButton();
        jKonjugate = new javax.swing.JButton();
        jTambah = new javax.swing.JButton();
        jKurang = new javax.swing.JButton();
        jKali = new javax.swing.JButton();
        jSquareButton = new javax.swing.JButton();
        jCubicButton = new javax.swing.JButton();
        jPolar = new javax.swing.JButton();
        jSalinHasil = new javax.swing.JButton();
        jClose = new javax.swing.JButton();
        jSquareRootButton = new javax.swing.JButton();
        jCubeRootButton = new javax.swing.JButton();
        jBagi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Bilangan Komplek 1 (Z1)");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Bilangan Komplek 2 (Z2)");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Hasil Operasi");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        fieldZ1.setForeground(new java.awt.Color(204, 204, 204));
        fieldZ1.setText("Masukkan angka");
        fieldZ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldZ1MouseClicked(evt);
            }
        });
        fieldZ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldZ1ActionPerformed(evt);
            }
        });
        fieldZ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldZ1KeyTyped(evt);
            }
        });

        label1.setText("+");

        label2.setText("+");

        label3.setText("i");

        label4.setText("i");

        fieldZ3.setForeground(new java.awt.Color(204, 204, 204));
        fieldZ3.setText("Masukkan angka");
        fieldZ3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldZ3MouseClicked(evt);
            }
        });
        fieldZ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldZ3ActionPerformed(evt);
            }
        });
        fieldZ3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldZ3KeyTyped(evt);
            }
        });

        fieldZ4.setForeground(new java.awt.Color(204, 204, 204));
        fieldZ4.setText("Masukkan angka");
        fieldZ4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldZ4MouseClicked(evt);
            }
        });
        fieldZ4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldZ4KeyTyped(evt);
            }
        });

        fieldZ5.setForeground(new java.awt.Color(204, 204, 204));
        fieldZ5.setText("Masukkan angka");
        fieldZ5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldZ5MouseClicked(evt);
            }
        });
        fieldZ5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldZ5KeyTyped(evt);
            }
        });

        fieldZ6.setForeground(new java.awt.Color(204, 204, 204));
        fieldZ6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldZ6KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldZ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldZ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldZ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldZ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldZ6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton1)
                                .addComponent(fieldZ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fieldZ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton2)
                                .addComponent(fieldZ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldZ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(fieldZ6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jClear.setText("Clear");
        jClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClearMouseClicked(evt);
            }
        });
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jModulus.setText("Modulus");
        jModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModulusActionPerformed(evt);
            }
        });

        jArgumen.setText("Argumen");
        jArgumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArgumenActionPerformed(evt);
            }
        });

        jKonjugate.setText("Konjugate");
        jKonjugate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKonjugateActionPerformed(evt);
            }
        });

        jTambah.setText("Tambah");
        jTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTambahActionPerformed(evt);
            }
        });

        jKurang.setText("Kurang");
        jKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKurangActionPerformed(evt);
            }
        });

        jKali.setText("Kali");
        jKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKaliActionPerformed(evt);
            }
        });

        jSquareButton.setText("z^2");
        jSquareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSquareButtonActionPerformed(evt);
            }
        });

        jCubicButton.setText("z^3");
        jCubicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCubicButtonActionPerformed(evt);
            }
        });

        jPolar.setText("Polar");
        jPolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPolarActionPerformed(evt);
            }
        });

        jSalinHasil.setText("Salin Hasil");
        jSalinHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalinHasilActionPerformed(evt);
            }
        });

        jClose.setText("Close");
        jClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseActionPerformed(evt);
            }
        });

        jSquareRootButton.setText("z^(1/2)");
        jSquareRootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSquareRootButtonActionPerformed(evt);
            }
        });

        jCubeRootButton.setText("z^(1/3)");
        jCubeRootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCubeRootButtonActionPerformed(evt);
            }
        });

        jBagi.setText("Bagi");
        jBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jClear)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSquareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jArgumen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCubicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKonjugate)
                            .addComponent(jKali, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSquareRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPolar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCubeRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSalinHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jModulus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSquareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jArgumen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jCubicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jKonjugate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jKali, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSquareRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPolar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jCubeRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jSalinHasil)
                .addGap(6, 6, 6)
                .addComponent(jClose))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih background display--", "Merah", "Kuning", "Hijau", "Biru", "Putih" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClearActionPerformed

    private void jModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModulusActionPerformed
        if (jRadioButton1.isSelected()) {
            Double hasil = this.z1.Modulus();
            jTextArea1.setText("Modulus dari\n" + this.z1.Display() + "\nadalah\n" + hasil.toString());
        } else if (jRadioButton2.isSelected()){
            Double hasil = this.z2.Modulus();
            jTextArea1.setText("Modulus dari\n" + this.z2.Display() + "\nadalah\n" + hasil.toString());
        } else {
            Double hasil = this.hasil.Modulus();
            jTextArea1.setText("Modulus dari\n" + this.hasil.Display() + "\nadalah\n" + hasil.toString());
        }
    }//GEN-LAST:event_jModulusActionPerformed
    
    private void jKonjugateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKonjugateActionPerformed
        if (jRadioButton1.isSelected()) {
            BilanganKompleks result = this.z1.Konjugat();
            jTextArea1.setText("Konjugat dari\n" + this.z1.Display() + "\nadalah\n" +  result.Display());
        } else if (jRadioButton2.isSelected()){
            BilanganKompleks result = this.z2.Konjugat();
            jTextArea1.setText("Konjugat dari\n" + this.z2.Display() + "\nadalah\n" + result.Display());
        } else {
            BilanganKompleks result = this.hasil.Konjugat();
            jTextArea1.setText("Konjugat dari\n" + this.hasil.Display() + "\nadalah\n" + result.Display());
        }
    }//GEN-LAST:event_jKonjugateActionPerformed

    private void jPolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPolarActionPerformed
        if (jRadioButton1.isSelected()) {
            BilanganKompleks result = this.z1.polar();
            jTextArea1.setText("Bentuk polar dari\n" + this.z1.Display() + "\nadalah\n" +  result.DspPolar());
        } else if (jRadioButton2.isSelected()){
            BilanganKompleks result = this.z2.polar();
            jTextArea1.setText("Bentuk polar dari\n" + this.z2.Display() + "\nadalah\n" + result.DspPolar());
        } else {
            BilanganKompleks result = this.hasil.polar();
            jTextArea1.setText("Bentuk polar dari\n" + this.hasil.Display() + "\nadalah\n" + result.DspPolar());
        }
    }//GEN-LAST:event_jPolarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void fieldZ1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldZ1KeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_fieldZ1KeyTyped

    private void fieldZ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldZ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldZ1ActionPerformed

    private boolean isFirstClick1 = true;
    private boolean isFirstClick2 = true;
    private boolean isFirstClick3 = true;
    private boolean isFirstClick4 = true;
    
    private void fieldZ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldZ1MouseClicked
        if (isFirstClick1){
            fieldZ1.setText("");
            isFirstClick1 = false;
        }
    }//GEN-LAST:event_fieldZ1MouseClicked

    private void fieldZ4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldZ4MouseClicked
        if (isFirstClick2){
            fieldZ4.setText("");
            isFirstClick2 = false;
        }
    }//GEN-LAST:event_fieldZ4MouseClicked

    private void fieldZ4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldZ4KeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_fieldZ4KeyTyped

    private void fieldZ5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldZ5MouseClicked
        if (isFirstClick4){
            fieldZ5.setText("");
            isFirstClick4 = false;
        }
    }//GEN-LAST:event_fieldZ5MouseClicked

    private void fieldZ5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldZ5KeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_fieldZ5KeyTyped

    private void fieldZ3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldZ3KeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_fieldZ3KeyTyped

    private void fieldZ3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldZ3MouseClicked
        if (isFirstClick3){
            fieldZ3.setText("");
            isFirstClick3 = false;
        }
    }//GEN-LAST:event_fieldZ3MouseClicked

    private void jCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jCloseActionPerformed

    private void jSquareRootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSquareRootButtonActionPerformed
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();

        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));

        ArrayList<BilanganKompleks> squareRoots;
        StringBuilder sb = new StringBuilder();
        String selectedComplexNumberDisplay = "";
    
        if (jRadioButton1.isSelected()) {
            squareRoots = this.z1.squareRoot();
            selectedComplexNumberDisplay = this.z1.Display();
            for (BilanganKompleks root : squareRoots) {
                sb.append(root.Display()).append("\n");
            }
        } else if (jRadioButton2.isSelected()) {
            squareRoots = this.z2.squareRoot();
            selectedComplexNumberDisplay = this.z2.Display();
            for (BilanganKompleks root : squareRoots) {
                sb.append(root.Display()).append("\n");
            }
        } else if (jRadioButton3.isSelected()) {
            squareRoots = this.hasil.squareRoot();
            selectedComplexNumberDisplay = this.hasil.Display();
            for (BilanganKompleks root : squareRoots) {
                sb.append(root.Display()).append("\n");
            }
        }
        jTextArea1.setText("Square root dari " + selectedComplexNumberDisplay + "\n=\n" + sb.toString());
        fieldZ6.setText(sb.toString());
    }//GEN-LAST:event_jSquareRootButtonActionPerformed

    private void jCubeRootButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();
    
        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));
    
        ArrayList<BilanganKompleks> cubeRoots;
        StringBuilder sb = new StringBuilder();
        String selectedComplexNumberDisplay = "";
    
        if (jRadioButton1.isSelected()) {
            cubeRoots = this.z1.cubeRoot();
            selectedComplexNumberDisplay = this.z1.Display();
            for (BilanganKompleks root : cubeRoots) {
                sb.append(root.Display()).append("\n");
            }
        } else if (jRadioButton2.isSelected()) {
            cubeRoots = this.z2.cubeRoot();
            selectedComplexNumberDisplay = this.z2.Display();
            for (BilanganKompleks root : cubeRoots) {
                sb.append(root.Display()).append("\n");
            }
        } else if (jRadioButton3.isSelected()) {
            cubeRoots = this.hasil.cubeRoot();
            selectedComplexNumberDisplay = this.hasil.Display();
            for (BilanganKompleks root : cubeRoots) {
                sb.append(root.Display()).append("\n");
            }
        }
        jTextArea1.setText("Cube root dari " + selectedComplexNumberDisplay + "\n=\n" + sb.toString());
        fieldZ6.setText(sb.toString());
    }

    private void jBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagiActionPerformed
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();
        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));
        
        this.hasil = this.z1.quotient(this.z2);
        jTextArea1.setText(this.z1.Display() + "\n+\n" + this.z2.Display() + "\n=\n" + this.hasil.Display());
        
        fieldZ6.setText(this.hasil.Display());
    }//GEN-LAST:event_jBagiActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED){
            if(!jComboBox1.getSelectedItem().toString().equals("--Pilih background display")){
                if(jComboBox1.getSelectedItem().toString().equals("Merah")){
                    jTextArea1.setBackground(Color.red);
                }
                else if(jComboBox1.getSelectedItem().toString().equals("Biru")){
                    jTextArea1.setBackground(Color.blue);
                }
                else if(jComboBox1.getSelectedItem().toString().equals("Kuning")){
                    jTextArea1.setBackground(Color.yellow);
                }
                else if(jComboBox1.getSelectedItem().toString().equals("Hijau")){
                    jTextArea1.setBackground(Color.green);
                }
                else if(jComboBox1.getSelectedItem().toString().equals("Putih")){
                jTextArea1.setBackground(Color.white);
                }
            }
            
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearMouseClicked
        clearTextFields();
        jTextArea1.setText("");
    }//GEN-LAST:event_jClearMouseClicked

    private void fieldZ6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldZ6KeyTyped
        fieldZ6.setEditable(false);
    }//GEN-LAST:event_fieldZ6KeyTyped

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        jTextArea1.setEditable(false);
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        fieldZ1.setEditable(true);
        fieldZ4.setEditable(true);
        fieldZ3.setEditable(false);
        fieldZ5.setEditable(false);
        
        
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        fieldZ1.setEditable(false);
        fieldZ4.setEditable(false);
        fieldZ3.setEditable(true);
        fieldZ5.setEditable(true);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahActionPerformed
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();
        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));
        
        this.hasil = this.z1.addition(this.z2);
        jTextArea1.setText(this.z1.Display() + "\n+\n" + this.z2.Display() + "\n=\n" + this.hasil.Display());
        
        fieldZ6.setText(hasil.Display());
    }//GEN-LAST:event_jTambahActionPerformed

    private void fieldZ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldZ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldZ3ActionPerformed

    private void jKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKurangActionPerformed
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();
        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));
        
        this.hasil = this.z1.subtraction(this.z2);
        jTextArea1.setText(this.z1.Display() + "\n+\n" + this.z2.Display() + "\n=\n" + hasil.Display());
        
        fieldZ6.setText(hasil.Display());
    }//GEN-LAST:event_jKurangActionPerformed

    private void jKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKaliActionPerformed
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();
        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));
        
        this.hasil = this.z1.multlipication(this.z2);
        jTextArea1.setText(this.z1.Display() + "\n+\n" + this.z2.Display() + "\n=\n" + hasil.Display());
        
        fieldZ6.setText(hasil.Display());
    }//GEN-LAST:event_jKaliActionPerformed

    private void jArgumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArgumenActionPerformed
        if (jRadioButton1.isSelected()) {
            Double hasil = this.z1.Argument();
            jTextArea1.setText("Argumen dari\n" + this.z1.Display() + "\nadalah\n" + hasil.toString());
        } else if (jRadioButton2.isSelected()){
            Double hasil = this.z2.Argument();
            jTextArea1.setText("Argumen dari\n" + this.z2.Display() + "\nadalah\n" + hasil.toString());
        } else {
            Double hasil = this.hasil.Argument();
            jTextArea1.setText("Argumen dari\n" + this.hasil.Display() + "\nadalah\n" + hasil.toString());
        }
    }//GEN-LAST:event_jArgumenActionPerformed

    private void jSalinHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalinHasilActionPerformed
        copyToClipboard();
    }//GEN-LAST:event_jSalinHasilActionPerformed
    private void copyToClipboard() {
        String resultText = jTextArea1.getText();
        StringSelection stringSelection = new StringSelection(resultText);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }
    private void jSquareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSquareButtonActionPerformed
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();
    
        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));
    
        BilanganKompleks squareResult = new BilanganKompleks(0, 0);
        String selectedComplexNumberDisplay = "";
    
        if (jRadioButton1.isSelected()) {
            squareResult = this.z1.square();
            selectedComplexNumberDisplay = this.z1.Display();
        } else if (jRadioButton2.isSelected()) {
            squareResult = this.z2.square();
            selectedComplexNumberDisplay = this.z2.Display();
        } else if (jRadioButton3.isSelected()) {
            squareResult = this.hasil.square();
            selectedComplexNumberDisplay = this.hasil.Display();
        }
    
        jTextArea1.setText("Square dari " + selectedComplexNumberDisplay + "\n=\n" + squareResult.Display());
    }//GEN-LAST:event_jSquareButtonActionPerformed

    private void jCubicButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String Rz1 = fieldZ1.getText();
        String Iz1 = fieldZ4.getText();
        String Rz2 = fieldZ3.getText();
        String Iz2 = fieldZ5.getText();
    
        this.z1.setRe(Double.parseDouble(Rz1));
        this.z1.setIm(Double.parseDouble(Iz1));
        this.z2.setRe(Double.parseDouble(Rz2));
        this.z2.setIm(Double.parseDouble(Iz2));
    
        BilanganKompleks cubicResult = new BilanganKompleks(0, 0);
        String selectedComplexNumberDisplay = "";
    
        if (jRadioButton1.isSelected()) {
            cubicResult = this.z1.cubic();
            selectedComplexNumberDisplay = this.z1.Display();
        } else if (jRadioButton2.isSelected()) {
            cubicResult = this.z2.cubic();
            selectedComplexNumberDisplay = this.z2.Display();
        } else if (jRadioButton3.isSelected()) {
            cubicResult = this.hasil.cubic();
            selectedComplexNumberDisplay = this.hasil.Display();
        }
    
        jTextArea1.setText("Cubic dari " + selectedComplexNumberDisplay + "\n=\n" + cubicResult.Display());
    }
    
    private void clearTextFields() {
        fieldZ1.setText("");
        fieldZ3.setText("");
        fieldZ4.setText("");
        fieldZ5.setText("");
        fieldZ6.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIkompleks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIkompleks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIkompleks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIkompleks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIkompleks().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldZ1;
    private javax.swing.JTextField fieldZ3;
    private javax.swing.JTextField fieldZ4;
    private javax.swing.JTextField fieldZ5;
    private javax.swing.JTextField fieldZ6;
    private javax.swing.JButton jArgumen;
    private javax.swing.JButton jBagi;
    private javax.swing.JButton jClear;
    private javax.swing.JButton jClose;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton jCubeRootButton;
    private javax.swing.JButton jCubicButton;
    private javax.swing.JButton jKali;
    private javax.swing.JButton jKonjugate;
    private javax.swing.JButton jKurang;
    private javax.swing.JButton jModulus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jPolar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton jSalinHasil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSquareButton;
    private javax.swing.JButton jSquareRootButton;
    private javax.swing.JButton jTambah;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
